apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-spring-app-ive
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-ive
  source:
    repoURL: https://github.com/williamsch/openshift-gitops-test.git
    targetRevision: master
    path: app
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
