apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-configs-ive
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-ive
  source:
    repoURL: https://github.com/williamsch/openshift-gitops-test.git
    targetRevision: master
    path: cluster
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
